### ISSUE TITLE
关于Android 4.4-5.x的适配问题

### ISSUE THREAD

**Issue by zhangxy1219** [liyuhaolol/LightImmersionMode#3]
首先感谢作者贡献出这个library。
我在实际使用过程中发现一个问题，如果在调用ImmersionConfiguration.Builder.setColor时传入的是浅色的颜色值（因为app的标题栏是浅色），这样在**4.4-5.x的非MIUI和Flyme系统的手机**上，状态栏会被设为浅色，导致状态栏中的内容无法看清。
看了一下源代码的实现，可以考虑在ImmersionHelper.statusBarFitToAPP函数里面的setStatusBarMode之后进行判断，如果ImmersionMode.getInstance().getPhoneType() == 4（代表无法使用浅色模式）且color是浅色的话，应该将状态栏设置为深色。可以在ImmersionMode里面提供配置这个深色的API，默认值为黑色。
希望作者帮忙加入这个适配功能，谢谢。

**Comment by liyuhaolol** [comment]
1，如果你只是为了设置为黑色或者单一深色不需要变换的话，你完全可以在Activity创建之前，通过android版本来阻止这个框架的运行，4.4版本以下statusBar默认就是为黑色，5.x版本statusBar默认颜色为colorPrimaryDark，你可以自己设置。并不需要框架进行额外的适配。
2，至于你说的浅色模式，字体看不清的问题，我这边的考量还是尽量减少对UI设计的改动，我给你改成别的颜色，最后你还是得跟你们UI说明原因。如果有确切有需要，还得待我忙完了以后，想一个万全的解决办法，再更新版本。

**Comment by zhangxy1219** [comment]
其实我的需求很简单：App效果图中的标题栏是浅色的，因此对于支持lightMode状态栏的系统（Android 6.0+、MIUI、魅族），就将状态栏设为和标题栏统一的颜色。对于不支持lightMode状态栏的系统需要将状态栏设置为深色（或者维持系统原本的颜色）。
因为在App代码中不方便判断“是否支持lightMode”，而我看到在library的实现里面可以判断，因此就想把“对于不支持lightMode状态栏的系统需要将状态栏设置为深色”这个功能放在library里面。

**Comment by liyuhaolol** [comment]
已经更新1.0.6版本，对于不支持浅色状态栏的api版本统一做了谷歌官方推荐的处理，当然会有一些副作用，请酌情选择是否使用。

**Comment by liyuhaolol** [comment]
已经更新1.0.6版本，对于不支持浅色状态栏的api版本统一做了谷歌官方推荐的处理，当然会有一些副作用，请酌情选择是否使用。请留意近期，如果有更好的办法，我会更新1.0.7。不在此做另行通知。
